# Generated by Django 4.2.25 on 2026-01-25 18:12

import credits.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, help_text='Montant demandé du crédit', max_digits=15)),
                ('taux_interet', models.DecimalField(decimal_places=2, help_text="Taux d'intérêt (en pourcentage, ex: 5.00 = 5%)", max_digits=5)),
                ('duree', models.PositiveIntegerField(help_text='Durée du crédit (en fonction du type)')),
                ('duree_type', models.CharField(choices=[('JOURS', 'Jours'), ('SEMAINES', 'Semaines'), ('MOIS', 'Mois')], default='MOIS', max_length=10)),
                ('methode_interet', models.CharField(choices=[('PRECOMPTE', 'Intérêt précompté (coupé à la source)'), ('POSTCOMPTE', "Intérêt postcompté (à l'échéance)")], default='PRECOMPTE', help_text="Méthode de calcul de l'intérêt : PRECOMPTE (intérêt déduit à la source, méthode par défaut) ou POSTCOMPTE (intérêt non déduit, compté à l'échéance)", max_length=12)),
                ('date_octroi', models.DateField(default=credits.models.get_default_date)),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('solde_restant', models.DecimalField(decimal_places=2, help_text='Solde restant à rembourser', max_digits=15)),
                ('statut', models.CharField(default='EN_COURS', max_length=20)),
                ('score', models.DecimalField(decimal_places=1, default=10.0, help_text='Score du crédit sur 10 (10 = excellent, 0 = très mauvais)', max_digits=3)),
                ('date_remboursement_final', models.DateField(blank=True, help_text='Date de remboursement complet du crédit (pour calcul du score)', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Remboursement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=15)),
                ('echeance', models.DateField(default=credits.models.get_default_date)),
                ('credit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remboursements', to='credits.credit')),
            ],
        ),
    ]
