# Generated by Django 4.2.25 on 2026-01-25 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('credits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='credit',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.client'),
        ),
        migrations.AddField(
            model_name='credit',
            name='membre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.membre'),
        ),
    ]
