# Generated by Django 4.2.25 on 2026-02-03 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='credit',
            options={'ordering': ['-date_octroi', '-id'], 'verbose_name': 'Crédit', 'verbose_name_plural': 'Crédits'},
        ),
        migrations.AlterModelOptions(
            name='remboursement',
            options={'ordering': ['-echeance', '-id'], 'verbose_name': 'Remboursement', 'verbose_name_plural': 'Remboursements'},
        ),
    ]
