# Generated by Django 4.2.25 on 2026-01-25 18:12

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cooperative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('sigle', models.CharField(blank=True, max_length=50, null=True)),
                ('forme_juridique', models.CharField(choices=[('COOPEC', "Cooperative d'epargne et de credit"), ('COOP_AGR', 'Cooperative agricole'), ('MUTUELLE', 'Mutuelle'), ('AUTRE', 'Autre')], default='COOPEC', max_length=20)),
                ('numero_rccm', models.CharField(blank=True, max_length=100, null=True, verbose_name='N° RCCM')),
                ('numero_id_nat', models.CharField(blank=True, max_length=100, null=True, verbose_name='N° Identification nationale')),
                ('date_creation', models.DateField(blank=True, null=True)),
                ('agrement', models.CharField(blank=True, max_length=100, null=True, verbose_name="N° d'agrement ministeriel")),
                ('pays', models.CharField(default='RDC', max_length=100)),
                ('province', models.CharField(max_length=100)),
                ('ville', models.CharField(max_length=100)),
                ('adresse', models.CharField(blank=True, max_length=255, null=True)),
                ('boite_postale', models.CharField(blank=True, max_length=50, null=True)),
                ('telephone', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('site_web', models.URLField(blank=True, null=True)),
                ('logo', models.ImageField(blank=True, help_text='Logo de la coopérative (formats acceptés: JPG, PNG, SVG)', null=True, upload_to='cooperatives/logos/')),
                ('date_enregistrement', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Coopérative',
                'verbose_name_plural': 'Coopératives',
                'ordering': ['-date_enregistrement'],
            },
        ),
        migrations.CreateModel(
            name='Membre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_compte', models.CharField(editable=False, max_length=20, unique=True)),
                ('type_membre', models.CharField(choices=[('PHYSIQUE', 'Personne physique'), ('MORALE', 'Personne morale (Entreprise)')], default='PHYSIQUE', help_text='Type de membre : personne physique ou morale', max_length=10)),
                ('adresse', models.CharField(blank=True, max_length=255, null=True)),
                ('telephone', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, help_text='Email (optionnel pour superadmin/admin, obligatoire pour membre/client)', max_length=99, null=True, unique=True)),
                ('password', models.CharField(help_text='Mot de passe (sera hashé automatiquement) - Minimum 6 caractères avec lettres, chiffres et caractères spéciaux', max_length=128)),
                ('date_adhesion', models.DateField(auto_now_add=True)),
                ('annee_adhesion', models.PositiveIntegerField(blank=True, help_text="Année d'adhésion (utilisée pour la génération du numéro de compte. Si non renseignée, utilise l'année courante)", null=True)),
                ('ville', models.CharField(blank=True, help_text='Ville de résidence', max_length=100, null=True)),
                ('profession', models.CharField(blank=True, help_text='Profession', max_length=100, null=True)),
                ('photo_profil', models.ImageField(blank=True, help_text='Photo de profil (formats acceptés: JPG, PNG)', null=True, upload_to='membres/photos/')),
                ('actif', models.BooleanField(default=False, editable=False)),
                ('nom', models.CharField(blank=True, help_text='Nom de famille (personne physique uniquement)', max_length=100, null=True)),
                ('postnom', models.CharField(blank=True, help_text='Postnom (personne physique uniquement)', max_length=100, null=True)),
                ('prenom', models.CharField(blank=True, help_text='Prénom (personne physique uniquement)', max_length=100, null=True)),
                ('sexe', models.CharField(blank=True, choices=[('M', 'Masculin'), ('F', 'Féminin')], help_text='Sexe (personne physique uniquement)', max_length=10, null=True)),
                ('date_naissance', models.DateField(blank=True, help_text='Date de naissance (personne physique uniquement)', null=True)),
                ('raison_sociale', models.CharField(blank=True, help_text='Raison sociale (personne morale uniquement)', max_length=255, null=True)),
                ('sigle', models.CharField(blank=True, help_text="Sigle de l'entreprise (personne morale uniquement)", max_length=50, null=True)),
                ('numero_immatriculation', models.CharField(blank=True, help_text="Numéro d'immatriculation RCCM (personne morale uniquement)", max_length=100, null=True)),
                ('forme_juridique', models.CharField(blank=True, help_text='Forme juridique (SARL, SA, etc.) (personne morale uniquement)', max_length=100, null=True)),
                ('representant_legal', models.CharField(blank=True, help_text='Nom du représentant légal (personne morale uniquement)', max_length=255, null=True)),
                ('secteur_activite', models.CharField(blank=True, help_text="Secteur d'activité (personne morale uniquement)", max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_compte', models.CharField(editable=False, max_length=20, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('postnom', models.CharField(blank=True, max_length=100, null=True)),
                ('prenom', models.CharField(max_length=100)),
                ('sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=10)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('adresse', models.CharField(blank=True, max_length=255, null=True)),
                ('telephone', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, help_text='Email (optionnel pour superadmin/admin, obligatoire pour membre/client)', max_length=99, null=True, unique=True)),
                ('password', models.CharField(help_text='Mot de passe (sera hashé automatiquement) - Minimum 6 caractères avec lettres, chiffres et caractères spéciaux', max_length=128)),
                ('profession', models.CharField(blank=True, help_text='Profession', max_length=100, null=True)),
                ('date_inscription', models.DateField(auto_now_add=True)),
                ('annee_adhesion', models.PositiveIntegerField(blank=True, help_text="Année d'adhésion (utilisée pour la génération du numéro de compte. Si non renseignée, utilise l'année courante)", null=True)),
                ('ville', models.CharField(blank=True, help_text='Ville de résidence', max_length=100, null=True)),
                ('photo_profil', models.ImageField(blank=True, help_text='Photo de profil (formats acceptés: JPG, PNG)', null=True, upload_to='clients/photos/')),
                ('actif', models.BooleanField(default=False, editable=False)),
                ('parrain', models.ForeignKey(blank=True, help_text='Membre qui a recommandé le client', null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.membre')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(blank=True, help_text='Email (optionnel pour superadmin/admin, obligatoire pour membre/client)', max_length=99, null=True, unique=True)),
                ('username', models.CharField(help_text="Nom d'utilisateur unique", max_length=150, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=150)),
                ('last_name', models.CharField(blank=True, max_length=150)),
                ('user_type', models.CharField(choices=[('SUPERADMIN', 'Super Administrateur'), ('ADMIN', 'Administrateur'), ('MEMBRE', 'Membre'), ('CLIENT', 'Client')], default='MEMBRE', help_text="Type d'utilisateur", max_length=20)),
                ('is_staff', models.BooleanField(default=False, help_text="Indique si l'utilisateur peut accéder à l'interface d'administration")),
                ('is_active', models.BooleanField(default=True, help_text='Indique si ce compte utilisateur est actif')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('client', models.OneToOneField(blank=True, help_text='Lien vers le profil Client (si user_type=CLIENT)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_account', to='users.client')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('membre', models.OneToOneField(blank=True, help_text='Lien vers le profil Membre (si user_type=MEMBRE)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_account', to='users.membre')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Utilisateur',
                'verbose_name_plural': 'Utilisateurs',
                'ordering': ['-date_joined'],
            },
        ),
    ]
