# Generated by Django 4.2.25 on 2026-02-03 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['-date_inscription', '-id'], 'verbose_name': 'Client', 'verbose_name_plural': 'Clients'},
        ),
        migrations.AlterModelOptions(
            name='membre',
            options={'ordering': ['-date_adhesion', '-id'], 'verbose_name': 'Membre', 'verbose_name_plural': 'Membres'},
        ),
    ]
