# Generated by Django 4.2.25 on 2026-01-25 18:12

import datetime
from django.db import migrations, models
import django.utils.timezone
import membres.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_compte', models.CharField(choices=[('VUE', 'Compte en vue'), ('BLOQUE', 'Compte bloqué')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='DonnatEpargne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mois', models.CharField(choices=[('JANVIER', 'Janvier'), ('FEVRIER', 'Février'), ('MARS', 'Mars'), ('AVRIL', 'Avril'), ('MAI', 'Mai'), ('JUIN', 'Juin'), ('JUILLET', 'Juillet'), ('AOUT', 'Août'), ('SEPTEMBRE', 'Septembre'), ('OCTOBRE', 'Octobre'), ('NOVEMBRE', 'Novembre'), ('DECEMBRE', 'Décembre')], max_length=100)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='DonnatPartSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_donnat', models.DateField(default=datetime.date.today)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mois', models.CharField(choices=[('JANVIER', 'Janvier'), ('FEVRIER', 'Février'), ('MARS', 'Mars'), ('AVRIL', 'Avril'), ('MAI', 'Mai'), ('JUIN', 'Juin'), ('JUILLET', 'Juillet'), ('AOUT', 'Août'), ('SEPTEMBRE', 'Septembre'), ('OCTOBRE', 'Octobre'), ('NOVEMBRE', 'Novembre'), ('DECEMBRE', 'Décembre')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FraisAdhesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_paiement', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='PartSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.PositiveIntegerField()),
                ('montant_souscrit', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Retrait',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=15)),
                ('date_operation', models.DateTimeField(default=django.utils.timezone.now)),
                ('motif', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Retrait',
                'verbose_name_plural': 'Retraits',
                'ordering': ['-date_operation'],
            },
        ),
        migrations.CreateModel(
            name='SouscriptEpargne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=100)),
                ('date_souscription', models.DateField(default=membres.models.get_default_date, help_text='Date de souscription (automatique)')),
                ('montant_souscrit', models.DecimalField(blank=True, decimal_places=2, help_text='Montant cible (optionnel, null = épargne illimitée)', max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SouscriptionPartSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_versements_prevu', models.PositiveIntegerField(help_text='Nombre de fois que le membre va payer cette part sociale')),
                ('date_souscription', models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
