# Generated by Django 4.2.25 on 2026-01-25 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('membres', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='souscriptionpartsocial',
            name='membre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.membre'),
        ),
        migrations.AddField(
            model_name='souscriptionpartsocial',
            name='partSocial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='membres.partsocial'),
        ),
        migrations.AddField(
            model_name='souscriptepargne',
            name='compte',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='membres.compte'),
        ),
        migrations.AddField(
            model_name='retrait',
            name='souscriptEpargne',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retrait_set', to='membres.souscriptepargne'),
        ),
        migrations.AddField(
            model_name='fraisadhesion',
            name='titulaire_client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.client'),
        ),
        migrations.AddField(
            model_name='fraisadhesion',
            name='titulaire_membre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.membre'),
        ),
        migrations.AddField(
            model_name='donnatpartsocial',
            name='souscription_part_social',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='donnatpartsocial_set', to='membres.souscriptionpartsocial'),
        ),
        migrations.AddField(
            model_name='donnatepargne',
            name='souscriptEpargne',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='membres.souscriptepargne'),
        ),
        migrations.AddField(
            model_name='compte',
            name='titulaire_client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.client'),
        ),
        migrations.AddField(
            model_name='compte',
            name='titulaire_membre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.membre'),
        ),
        migrations.AlterUniqueTogether(
            name='souscriptionpartsocial',
            unique_together={('membre', 'partSocial')},
        ),
    ]
