# Generated by Django 4.2.25 on 2026-02-03 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('membres', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='compte',
            options={'ordering': ['-id'], 'verbose_name': 'Compte', 'verbose_name_plural': 'Comptes'},
        ),
        migrations.AlterModelOptions(
            name='donnatepargne',
            options={'ordering': ['-id'], 'verbose_name': "Don d'épargne", 'verbose_name_plural': "Dons d'épargne"},
        ),
        migrations.AlterModelOptions(
            name='fraisadhesion',
            options={'ordering': ['-date_paiement', '-id'], 'verbose_name': "Frais d'adhésion", 'verbose_name_plural': "Frais d'adhésion"},
        ),
    ]
