# Generated by Django 4.2.25 on 2026-01-25 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rapport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_rapport', models.CharField(choices=[('MENSUEL', 'Rapport mensuel'), ('ANNUEL', 'Rapport annuel'), ('APPORTS', 'Rapport des apports'), ('INTERETS', 'Rapport des intérêts'), ('CAISSE', 'Rapport de caisse'), ('CREDITS', 'Rapport des crédits'), ('TRANSACTIONS', 'Rapport des transactions')], help_text='Type de rapport', max_length=20)),
                ('periode_mois', models.IntegerField(blank=True, help_text='Mois (1-12)', null=True)),
                ('periode_annee', models.IntegerField(help_text='Année')),
                ('date_generation', models.DateTimeField(auto_now_add=True, help_text='Date de génération')),
                ('contenu', models.JSONField(help_text='Contenu du rapport (JSON)')),
                ('fichier_pdf', models.FileField(blank=True, help_text='Fichier PDF du rapport (optionnel)', null=True, upload_to='rapports/pdf/')),
                ('envoye', models.BooleanField(default=False, help_text='Rapport envoyé par email')),
                ('date_envoi', models.DateTimeField(blank=True, help_text="Date d'envoi", null=True)),
            ],
            options={
                'verbose_name': 'Rapport',
                'verbose_name_plural': 'Rapports',
                'ordering': ['-date_generation'],
            },
        ),
        migrations.CreateModel(
            name='EnvoiEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destinataire_type', models.CharField(choices=[('MEMBRE', 'Membre'), ('CLIENT', 'Client'), ('ADMIN', 'Administrateur')], help_text='Type de destinataire', max_length=10)),
                ('destinataire_id', models.IntegerField(help_text='ID du destinataire (membre ou client)')),
                ('email_destinataire', models.EmailField(help_text='Email du destinataire', max_length=254)),
                ('sujet', models.CharField(help_text="Sujet de l'email", max_length=255)),
                ('message', models.TextField(help_text="Message de l'email")),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('EN_COURS', 'En cours'), ('ENVOYE', 'Envoyé'), ('ECHEC', 'Échec')], default='EN_ATTENTE', help_text="Statut de l'envoi", max_length=20)),
                ('date_envoi', models.DateTimeField(blank=True, help_text="Date d'envoi", null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True, help_text='Date de création')),
                ('erreur', models.TextField(blank=True, help_text="Message d'erreur si échec", null=True)),
                ('rapport', models.ForeignKey(blank=True, help_text='Rapport associé (si applicable)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='envois', to='rapports.rapport')),
            ],
            options={
                'verbose_name': 'Envoi Email',
                'verbose_name_plural': 'Envois Emails',
                'ordering': ['-date_creation'],
            },
        ),
    ]
