# Generated by Django 4.2.25 on 2026-02-03 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rapports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rapport',
            name='type_rapport',
            field=models.CharField(choices=[('MENSUEL', 'Rapport mensuel'), ('ANNUEL', 'Rapport annuel'), ('APPORTS', 'Rapport des apports'), ('INTERETS', 'Rapport des intérêts'), ('CAISSE', 'Rapport de caisse'), ('CREDITS', 'Rapport des crédits'), ('OPERATIONS', 'Rapport des opérations')], help_text='Type de rapport', max_length=20),
        ),
    ]
