# Generated by Django 4.2.25 on 2026-01-25 18:12

import caisse.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CaisseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text='Nom du type de caisse (ex: Airtel Money, Orange Money, Banque)', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description du type de caisse', null=True)),
                ('image', models.ImageField(blank=True, help_text='Logo/Image du type de caisse (formats acceptés: JPG, PNG, SVG)', null=True, upload_to='caissetypes/logos/')),
                ('last_updated', models.DateTimeField(auto_now=True, help_text='Date de dernière mise à jour')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date de création')),
            ],
            options={
                'verbose_name': 'Type de caisse',
                'verbose_name_plural': 'Types de caisse',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Caissetypemvt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=caisse.models.get_default_date, help_text='Date du mouvement (automatique)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Mouvement de type de caisse',
                'verbose_name_plural': 'Mouvements de type de caisse',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Depenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(help_text='Libellé de la dépense', max_length=200)),
                ('uniter', models.CharField(help_text='Unité de mesure (ex: kg, litre, pièce, etc.)', max_length=50)),
                ('quantite', models.DecimalField(decimal_places=2, help_text='Quantité', max_digits=10)),
                ('pu', models.DecimalField(decimal_places=2, help_text='Prix unitaire', max_digits=15)),
                ('date_depense', models.DateField(default=django.utils.timezone.now, help_text='Date de la dépense')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Dépense',
                'verbose_name_plural': 'Dépenses',
                'ordering': ['-date_depense', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numTrans', models.CharField(editable=False, help_text='Numéro de transaction (auto-généré)', max_length=20, unique=True)),
                ('type', models.CharField(choices=[('ENTREE', 'Entrée'), ('SORTIE', 'Sortie'), ('ENTREE_APRES_CALCUL_FRAIS_GESTION', 'Entrée après calcul des frais de gestion')], help_text='Type de transaction', max_length=50)),
                ('motif', models.CharField(help_text='Motif de la transaction', max_length=255)),
                ('montant', models.DecimalField(decimal_places=2, help_text='Montant de la transaction', max_digits=15)),
                ('date', models.DateField(default=caisse.models.get_default_date, help_text='Date de la transaction (automatique)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
