# Generated by Django 4.2.25 on 2026-01-25 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('caisse', '0001_initial'),
        ('credits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='credit',
            field=models.ForeignKey(blank=True, help_text='Crédit lié à cette transaction', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='credits.credit'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='depense',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='caisse.depenses'),
        ),
    ]
