# Generated by Django 4.2.25 on 2026-01-25 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('credits', '0001_initial'),
        ('caisse', '0002_initial'),
        ('membres', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='fraisAdhesion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='membres.fraisadhesion'),
        ),
        migrations.AddField(
            model_name='caissetypemvt',
            name='caissetype',
            field=models.ForeignKey(help_text='Type de caisse (obligatoire)', on_delete=django.db.models.deletion.PROTECT, related_name='mouvements', to='caisse.caissetype'),
        ),
        migrations.AddField(
            model_name='caissetypemvt',
            name='depense',
            field=models.ForeignKey(blank=True, help_text='Dépense liée (optionnel)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='caissetype_mouvements', to='caisse.depenses'),
        ),
        migrations.AddField(
            model_name='caissetypemvt',
            name='donnatepargne',
            field=models.ForeignKey(blank=True, help_text="Don d'épargne lié (optionnel)", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='caissetype_mouvements', to='membres.donnatepargne'),
        ),
        migrations.AddField(
            model_name='caissetypemvt',
            name='donnatpartsocial',
            field=models.ForeignKey(blank=True, help_text='Don de part sociale lié (optionnel)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='caissetype_mouvements', to='membres.donnatpartsocial'),
        ),
        migrations.AddField(
            model_name='caissetypemvt',
            name='fraisadhesion',
            field=models.ForeignKey(blank=True, help_text="Frais d'adhésion lié (optionnel)", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='caissetype_mouvements', to='membres.fraisadhesion'),
        ),
        migrations.AddField(
            model_name='caissetypemvt',
            name='remboursement',
            field=models.ForeignKey(blank=True, help_text='Remboursement lié (optionnel)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='caissetype_mouvements', to='credits.remboursement'),
        ),
        migrations.AddField(
            model_name='caissetypemvt',
            name='retrait',
            field=models.ForeignKey(blank=True, help_text='Retrait lié (optionnel)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='caissetype_mouvements', to='membres.retrait'),
        ),
        migrations.AddField(
            model_name='caissetypemvt',
            name='transaction',
            field=models.ForeignKey(blank=True, help_text='Transaction liée (optionnel)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='caissetype_mouvements', to='caisse.transaction'),
        ),
    ]
