# Generated by Django 4.2.25 on 2026-02-03 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caisse', '0004_add_credit_to_caissetypemvt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caissetypemvt',
            name='transaction',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
