# Generated by Django 4.2.25 on 2026-02-06 14:50

import caisse.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('caisse', '0005_remove_caissetypemvt_transaction_delete_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonDirect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, help_text='Montant du don', max_digits=15)),
                ('date_don', models.DateField(default=caisse.models.get_default_date, help_text='Date du don')),
                ('libelle', models.CharField(blank=True, help_text='Description/libellé du don (optionnel)', max_length=200, null=True)),
                ('donateur_nom', models.CharField(blank=True, help_text='Nom du donateur (optionnel)', max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Don direct',
                'verbose_name_plural': 'Dons directs',
                'ordering': ['-date_don', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='caissetypemvt',
            name='dondirect',
            field=models.ForeignKey(blank=True, help_text='Don direct lié (optionnel)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='caissetype_mouvements', to='caisse.dondirect'),
        ),
    ]
